Feature/get generated reports geo 66
bcgov/fin-pay-transparency pull request #154
Opened 2024-01-12 22:07 UTC by jer3k

https://finrms.atlassian.net/jira/software/projects/GEO/boards/70/backlog?selectedIssue=GEO-66

2024-01-12 23:45 UTC, banders commented on frontend/src/common/apiService.js
> +      throw new Error('Unable to fetch NAICS codes from API');
change "NAICS codes" to "published reports"

2024-01-12 23:45 UTC, banders commented on frontend/src/common/apiService.js
> +      console.log(`Failed to get NAICS from API - ${e}`);
change "NAICS" to "published reports"

2024-01-15 18:20 UTC, sukanya-rath requested changes

2024-01-15 18:20 UTC, sukanya-rath commented on backend/src/v1/routes/report-routes.ts
> +  '/published',
change the url - remove /published , add a` query parameter` called `report_status` (which can be take values either `published` or `draft`)

2024-01-15 19:17 UTC, banders reviewed
I agree with Sukanya's suggestion, and I have no additional suggestions.  Nice job with the unit tests.

2024-01-17 19:49 UTC, banders commented on backend/src/v1/routes/report-routes.ts
> +  auth.isValidBackendToken(),
Sonar identified a possible bug here.  auth.isValidBackendToken() needs to be wrapped in a call to utils.asyncHandler(...).  See example in code-routes.ts.

2024-01-17 20:11 UTC, banders commented on backend/src/v1/services/report-service.ts
> +        pay_transparency_report: {
Can we sort the reports by report start date (newest to oldest), then secondarily by update date (newest to oldest)?

2024-01-17 20:16 UTC, banders commented on frontend/src/common/apiService.js
> +      console.log(`Failed to get published reports from API - ${e}`);
remove the word 'published' from the log statement.

2024-01-18 00:45 UTC, banders approved these changes

2024-01-18 02:31 UTC, merged