task/sonar-fix-sprint-9-geo-355
bcgov/fin-pay-transparency pull request #322
Opened 2024-03-19 19:52 UTC by andybcgov

Sonar fixes sprint 9

https://finrms.atlassian.net/browse/GEO-355

2024-03-20 16:26 UTC, sukanya-rath requested changes

2024-03-20 16:26 UTC, sukanya-rath commented on doc-gen-service/src/templates/report-template-header.html
> +    color: #cccccc;
remove this change

2024-03-20 16:26 UTC, sukanya-rath commented on doc-gen-service/src/templates/report-template-header.html
> +    font-size: 100px;
remove this change

2024-03-21 01:43 UTC, sukanya-rath approved these changes

2024-03-21 01:44 UTC, sukanya-rath requested changes
please fix the sonar warning

2024-03-21 15:41 UTC, andybcgov commented
> please fix the sonar warning

@sukanya-rath There's an error generating the report. I checked quickly but couldn't find the cause, I'll keep looking. FYI - my CSV is 5KB .
![image](https://github.com/bcgov/fin-pay-transparency/assets/118761047/429fb325-1aa2-4640-905b-2664700afb50)

2024-03-26 19:58 UTC, andybcgov commented
> please fix the sonar warning

@sukanya-rath I think I've fixed this already. Not sure though.

2024-03-27 00:02 UTC, sukanya-rath approved these changes

2024-03-27 00:02 UTC, merged