feat: geo 1049 dashboard public announcements backend implementation
bcgov/fin-pay-transparency pull request #751
Opened 2024-09-13 17:52 UTC by goemen

# Description

dashboard public announcements backend implementation

Fixes # ([issue](https://finrms.atlassian.net/browse/GEO-1049))

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2024-09-16 21:47 UTC, sukanya-rath submitted a review, later dismissed

2024-09-16 21:47 UTC, sukanya-rath commented on backend/src/admin-app.ts
> +import dashboardMetricsRoutes from './v1/routes/dashboard-metrics-routes';
make the folder structure for routes to be routes/dashboard - followed by individual file names - announcement-metrics

2024-09-17 17:02 UTC, banders reviewed
Can we rename routes/dashboard/dashboard.spec.ts to index.spec.ts?

2024-09-17 17:10 UTC, banders requested changes
My preference would be that we don't create a new service (dashboard-metrics-service).  Instead, the function to return announcement-related metrics could go into the existing announcement-service, and the reports-related metrics could go into the existing admin-report-service.  

In other words, let's organize our services according to which data they operate on, not by who/what will consume its data.  (The consumers of a service can change as systems evolve.)

2024-09-18 20:48 UTC, banders approved these changes

2024-09-18 22:06 UTC, merged